apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-gateway-private
  namespace: traefik
  annotations:
    traefik.io/service.serversscheme: h2c
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      protocol: HTTP
      port: 8001
      allowedRoutes:
        namespaces:
          from: All
    - name: local-bigd-no
      protocol: HTTPS
      port: 8444
      hostname: "*.local.bigd.no"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: local-bigd-no-tls
            namespace: cert-manager
  infrastructure:
    parametersRef:
      group: traefik.io
      kind: Middleware
      name: redirect-to-https
      namespace: traefik
