apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-gateway
  namespace: traefik
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      protocol: HTTP
      port: 8000
      allowedRoutes:
        namespaces:
          from: All
    - name: local-bigd-no
      protocol: HTTPS
      port: 8443
      hostname: "*.local.bigd.no"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: local-bigd-no-tls
            namespace: cert-manager
    - name: bigd-no
      protocol: HTTPS
      port: 8443
      hostname: "*.bigd.no"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: bigd-no-tls
            namespace: cert-manager
    - name: nordbye-it
      protocol: HTTPS
      port: 8443
      hostname: "*.nordbye.it"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: nordbye-it-tls
            namespace: cert-manager
