apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"

resources:
  - namespace.yaml
  - gateway.yaml
  - http-redirect.yaml
  - middleware-local-only.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    includeCRDs: true
    namespace: traefik
    version: 38.0.1
    releaseName: traefik
    valuesFile: ./values.yaml
