apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - dashboard-route.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    includeCRDs: true
    namespace: traefik
    version: 38.0.1
    releaseName: traefik
    valuesFile: ./values.yaml
