apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"

resources:
  - namespace.yaml
  - gateway-public.yaml
  - gateway-private.yaml
  - service-public.yaml
  - service-private.yaml
  - httproute-dashboard.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    includeCRDs: false
    namespace: traefik
    version: 38.0.2
    releaseName: traefik
    valuesFile: ./values.yaml
