apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: local-network-only
  namespace: traefik
spec:
  ipAllowList:
    sourceRange:
      - 10.0.0.0/8 # Private network
      - 172.16.0.0/12 # Private network
      - 192.168.0.0/16 # Private network
      - 127.0.0.1/32 # Localhost
