apiVersion: v1
kind: Service
metadata:
  name: traefik-private
  namespace: traefik
  annotations:
    lbipam.cilium.io/ips: "10.3.10.102"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: web
      port: 80
      targetPort: 8001
      protocol: TCP
    - name: websecure
      port: 443
      targetPort: 8444
      protocol: TCP
