apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr-stack

resources:
  - namespace.yaml
  - sonarr.yaml
  - radarr.yaml
  - bazarr.yaml
  - flaresolverr.yaml
 # - tdarr.yaml
 # - huntarr.yaml
 # - cleanuparr.yaml
  - httproutes.yaml
