apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

namespace: falco

helmCharts:
  - name: falco
    repo: https://falcosecurity.github.io/charts
    includeCRDs: true
    namespace: falco
    version: "4.22.0"
    releaseName: falco
    valuesFile: ./values.yaml
