---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "3"

resources:
  - namespace.yaml

namespace: velero

helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    includeCRDs: true
    namespace: velero
    version: 11.2.0
    releaseName: velero
    valuesFile: ./values.yaml
