apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"

resources:
  - namespace.yaml

namespace: syno-nfs-prov

helmCharts:
  - name: nfs-subdir-external-provisioner
    repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    includeCRDs: true
    namespace: syno-nfs-prov
    version: 4.0.18
    releaseName: syno-nfs-prov
    valuesFile: ./values.yaml
