replicaCount: 1

nfs:
  server: "10.3.10.10"
  path: "/volume1/k8s-volumes/talos"

storageClass:
  create: true
  name: syno-nfs
  defaultClass: true
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  archiveOnDelete: true
