apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - arc-github-ext-secret.yaml

namespace: arc-runners

helmCharts:
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    includeCRDs: true
    namespace: arc-runners
    version: 0.13.0
    releaseName: arc-runner-set
    valuesFile: ./values.yaml