apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tautulli
  namespace: plex-media-stack
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
      sectionName: bigd-no
  hostnames:
    - tautulli.bigd.no
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: tautulli
          port: 8181
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: overseerr
  namespace: plex-media-stack
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
      sectionName: bigd-no
  hostnames:
    - overseerr.bigd.no
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: overseerr
          port: 5055
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
