apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - plex-pvc.yaml
  - plex-deployment.yaml
  - plex-service.yaml
  - tautulli-pvc.yaml
  - tautulli-deployment.yaml
  - tautulli-service.yaml
  - overseerr-pvc.yaml
  - overseerr-deployment.yaml
  - overseerr-service.yaml
  - httproutes.yaml
