apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-config
  namespace: gluetun-vpn
data:
  VPN_SERVICE_PROVIDER: "private internet access"
  VPN_TYPE: "openvpn"
  SERVER_REGIONS: "Switzerland"
  FIREWALL_OUTBOUND_SUBNETS: "10.0.0.0/8"
  # Allow incoming connections on port 80 for nginx (and later qBittorrent, Prowlarr etc)
  FIREWALL_INPUT_PORTS: "80,8000"
  # Disable HTTP control server authentication for internal use
  HTTPPROXY_STEALTH: "on"
  TZ: "Europe/Oslo"
