apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pia-secret.yaml
  - gluetun-config.yaml
  - pvcs.yaml
  - service.yaml
  - gluetun.yaml
  - httproute.yaml
