apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pia-credentials-ext-secret
  namespace: gluetun-vpn
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: pia-credentials
    creationPolicy: Owner
  data:
    - secretKey: OPENVPN_USER
      remoteRef:
        key: "1c37f2f4-0319-43f1-a373-b3c000f8cd7b"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: OPENVPN_PASSWORD
      remoteRef:
        key: "3a22933d-c204-4528-bcd9-b3c000f8e583"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
