apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metadata-pvc
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-local
  resources:
    requests:
      storage: 5Gi
