apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"

resources:
  - namespace.yaml
  - httproutes.yaml

helmCharts:
  - name: victoria-metrics-single
    repo: https://victoriametrics.github.io/helm-charts
    namespace: victoria-metrics
    version: 0.27.0
    releaseName: vmsingle
    valuesFile: ./values.yaml
