---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-local
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
parameters:
  csi.storage.k8s.io/fstype: ext4
  storage: local-lvm
  cache: writethrough
  ssd: "true"
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.kubernetes.io/zone
        values:
          - hyper1

---
