---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-local
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  csi.storage.k8s.io/fstype: ext4
  storage: local-lvm
  cache: writethrough
  ssd: "true"
  backup: "true"
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

---
