---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: proxmox-snapshot
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: csi.proxmox.sinextra.dev
deletionPolicy: Delete
parameters:
  # Copy snapshots to hyper2 nodes for geo-redundancy
  # If omitted, snapshots stay on same node as source volume
  zone: hyper2
