apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bigd-no
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "201"
spec:
  secretName: bigd-no-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.bigd.no"
  dnsNames:
    - "bigd.no"
    - "*.bigd.no"
