apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nordbye-it
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "201"
spec:
  secretName: nordbye-it-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.nordbye.it"
  dnsNames:
    - "nordbye.it"
    - "*.nordbye.it"
