apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "3"

resources:
  - namespace.yaml
  - httproutes.yaml
  - grafana-admin-secret.yaml

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    namespace: grafana
    version: 10.4.0
    releaseName: grafana
    valuesFile: ./values.yaml
