apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nordbye
  namespace: portfolio
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway-public
      namespace: traefik
  hostnames:
    - nordbye.it
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: nordbye-service
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
