apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - homarr-db-ext-secret.yaml

namespace: homarr

helmCharts:
  - name: homarr
    repo: https://homarr-labs.github.io/charts/
    includeCRDs: true
    namespace: homarr
    version: 8.6.0
    releaseName: homarr
    valuesFile: ./values.yaml
