replicaCount: 1
strategyType: RollingUpdate

env:
  TZ: "Europe/Oslo"

envSecrets:
  dbEncryption:
    existingSecret: homarr-db-secret
    key: db-encryption-key

persistence:
  homarrDatabase:
    enabled: true
    storageClassName: proxmox-local
    size: "1Gi"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - hyper1

rbac:
  enabled: true

httproute:
  enabled: false

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 3000
