replicaCount: 1
strategyType: RollingUpdate

env:
  TZ: "Europe/Oslo"

envSecrets:
  dbEncryption:
    existingSecret: homarr-db-secret
    key: db-encryption-key

persistence:
  homarrDatabase:
    enabled: true
    storageClassName: syno-nfs
    size: "1Gi"

rbac:
  enabled: true

httproute:
  enabled: false

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 3000
