replicaCount: 1
strategyType: RollingUpdate

env:
  TZ: "Europe/Oslo"

envSecrets:
  dbEncryption:
    existingSecret: homarr-db-secret
    key: db-encryption-key

persistence:
  homarrDatabase:
    enabled: true
    storageClassName: syno-nfs
    size: "1Gi"

rbac:
  enabled: true

httproute:
  enabled: true
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
      sectionName: bigd-no
  hostnames:
    - hub.bigd.no
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: homarr
          port: 7575
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
      filters: []

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 3000
