apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage

resources:
  - namespace.yaml
  - httproute.yaml

helmCharts:
  - name: homepage
    repo: https://jameswynn.github.io/helm-charts
    version: 2.1.0
    releaseName: homepage
    namespace: homepage
    valuesFile: values.yaml
