apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-api-keys
  namespace: homepage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: homepage-api-keys
    creationPolicy: Owner
  data:
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: 0350d8a3-05eb-4201-859a-b3c200a15fc4
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: 453e06b8-66bc-4d5b-94ac-b3c200a12c85
