apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-api-keys
  namespace: homepage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: homepage-api-keys
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_SONARR_API_KEY
      remoteRef:
        key: 0350d8a3-05eb-4201-859a-b3c200a15fc4
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_RADARR_API_KEY
      remoteRef:
        key: 453e06b8-66bc-4d5b-94ac-b3c200a12c85
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_PROWLARR_API_KEY
      remoteRef:
        key: 72898bab-76d9-4aa9-9c3a-b3c200a71c16
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_BAZARR_API_KEY
      remoteRef:
        key: 384c2a48-332f-4d6b-8175-b3c200a75a98
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_OVERSEERR_API_KEY
      remoteRef:
        key: ee160c65-8ff8-469f-8f64-b3c200a77edd
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_QBITTORRENT_USERNAME
      remoteRef:
        key: 7d9a94e9-a067-4302-bda0-b3c40101aa9d
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_QBITTORRENT_PASSWORD
      remoteRef:
        key: b4b0041d-0e5a-4358-825b-b3c40101c3e3
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
