apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-api-keys
  namespace: homepage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: homepage-api-keys
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_SONARR_API_KEY
      remoteRef:
        key: 0350d8a3-05eb-4201-859a-b3c200a15fc4
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_RADARR_API_KEY
      remoteRef:
        key: 453e06b8-66bc-4d5b-94ac-b3c200a12c85
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
