replicaCount: 1

nfs:
  server: "nas.local.bigd.no"
  path: "/volume1/k8s-volumes/talos"

storageClass:
  create: true
  name: syno-nfs
  defaultClass: false
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  archiveOnDelete: true
