apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-2"

resources:
  - namespace.yaml
  - cloudflare-token-secret.yaml
  - certificates/bigd-no.yaml
  - certificates/local-bigd-no.yaml
  - certificates/nordbye-it.yml
  - issuers/letsencrypt-prod.yaml
  - reference-grant.yaml

namespace: cert-manager
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    includeCRDs: true
    namespace: cert-manager
    version: 1.19.2
    releaseName: cert-manager
    valuesFile: ./values.yaml
