---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: victoriametrics
  namespace: victoria-metrics
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway-private
      namespace: traefik
  hostnames:
    - victoriametrics.local.bigd.no
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: vmsingle-victoria-metrics-single-server
          port: 8428
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
