apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

resources:
  - namespace.yaml
  - cluster_issuer.yaml
  - bitwarden-certificate.yaml
  - clustersecretstore-bitwarden.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io/
    includeCRDs: true
    namespace: external-secrets
    version: 1.2.0
    releaseName: external-secrets-operator
    valuesFile: ./values.yaml
