apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - project-apps.yaml
  - project-infra.yaml
  - apps.yaml
  - infra.yaml
#- httproute.yaml
namespace: argocd

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    includeCRDs: true
    namespace: argocd
    version: 9.1.7
    releaseName: argocd
    valuesFile: ./values.yaml
