apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - project-homelab.yaml

namespace: argocd

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    includeCRDs: false
    namespace: argocd
    version: 8.2.7
    releaseName: argo-cd
    valuesFile: ./values.yaml
