global:
  domain: argocd.local.bigd.no

crds:
  install: true

configs:
  params:
    server.insecure: true
  cm:
    kustomize.buildOptions: "--enable-helm"
    exec.enabled: "true"
    accounts.mnordbye: apiKey, login
  rbac:
    policy.csv: |
      p, role:admin-mnordbye, applications, *, */*, allow
      p, role:admin-mnordbye, clusters, *, *, allow
      p, role:admin-mnordbye, repositories, *, *, allow
      p, role:admin-mnordbye, logs, *, *, allow
      p, role:admin-mnordbye, exec, *, */*, allow
      p, role:admin-mnordbye, projects, *, *, allow
      g, mnordbye, role:admin-mnordbye
  secret:
    createSecret: false

server:
  replicas: 1
  service:
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: "10.3.10.100"
  ingress:
    enabled: false
  httproute:
    enabled: true
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: traefik-gateway-private
        namespace: traefik
    hostnames:
      - argocd.local.bigd.no

dex:
  enabled: false

notifications:
  enabled: true

applicationSet:
  enabled: true

redis-ha:
  enabled: false

controller:
  replicas: 1

repoServer:
  replicas: 1
