apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

commonAnnotations:
  argocd.argoproj.io/sync-options: Prune=false
# Disabled - uncomment to re-enable
# helmCharts:
#   - name: opentelemetry-collector
#     repo: https://open-telemetry.github.io/opentelemetry-helm-charts
#     version: 0.142.1
#     releaseName: otel-collector
#     namespace: monitoring
#     valuesFile: values.yaml
