apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-2"

namespace: kube-system

resources:
  - l2-announcement-policy.yaml
  - loadbalancer-ippool.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    includeCRDs: true
    namespace: kube-system
    version: 1.19.0-pre.4
    releaseName: cilium
    valuesFile: ./values.yaml
