apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - ippool.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    includeCRDs: true
    namespace: kube-system
    version: 1.16.5
    releaseName: cilium
    valuesFile: ./values.yaml
